---
- name: Deploy ABC Bank to EC2 Production
  hosts: production  # 1. This correctly targets 'production' from your inventory.yml
  become: yes      # 2. This runs 'sudo' on the EC2, where 'ubuntu' has permission
  vars:
    app_name: abc-bank-automated
    app_port: 3001
    github_repo: https://github.com/KaViNdYa09/abc-bank-pipeline.git
    deploy_path: /home/ubuntu/abc-bank-deploy

  tasks:
    - name: Install Docker on EC2
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group (on EC2)
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Pull latest code from GitHub (to EC2)
      git:
        repo: "{{ github_repo }}"
        dest: "{{ deploy_path }}"
        version: main
        force: yes # Overwrite any local changes

    - name: Stop existing container
      community.docker.docker_container:
        name: "{{ app_name }}"
        state: absent
      ignore_errors: yes

    - name: Build Docker image on EC2
      community.docker.docker_image:
        name: abc-bank
        tag: latest
        source: build
        build:
          path: "{{ deploy_path }}" # Build from the code we just pulled
          pull: yes
        state: present

    - name: Run Docker container on EC2
      community.docker.docker_container:
        name: "{{ app_name }}"
        image: abc-bank:latest
        state: started
        restart_policy: always
        ports:
          - "{{ app_port }}:3000" # Map 3001 (EC2) to 3000 (container)

    - name: Health check (on EC2)
      uri:
        url: "http://localhost:{{ app_port }}/api/health" # 3. Uses the correct health path
        status_code: 200
      retries: 5
      delay: 3
